sonar.projectKey=microservices-notes-app
sonar.projectName=Microservices Notes App
sonar.projectVersion=1.0

sonar.sources=api-gateway,user-service,notes-service,frontend
sonar.exclusions=**/node_modules/**,**/*.test.js,**/docker-compose.yml

sonar.javascript.lcov.reportPaths=coverage/lcov.info
